### ISSUE TITLE
GenServer terminated with an error when mix ecto.setup

### ISSUE THREAD

**Issue by zacky1972** [thehaigo/live_canvas#1]
Thank you for implementing LiveCanvas.

I got the following error when `mix ecto.setup`:

```elixir
14:32:29.687 [error] GenServer #PID<0.4138.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

14:32:29.691 [error] GenServer #PID<0.4144.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for LiveCanvas.Repo couldn't be created: killed
```

My environments are as follows:

```bash
% elixir -v 
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

I run it on macOS Catalina 10.15.7.

Thank you.

**Comment by zacky1972** [comment]
```
dbにpostgresql を使っていますので、Installと起動をお願いします
https://github.com/thehaigo/live_canvas/blob/e09fc42de7e8a65a0a98dd13c93feee8731f2703/config/dev.exs#L4-L6
作成したuserとpassに変更するか
user postgres pass postgres で作成してroleにsuperuser を付与してください
```

Thank you for your reply, @thehaigo .

I installed and started postgresql, successfully, as follows:

```bash
% brew install postgres
% brew services start postgresql
```

However, I got the following error:

```bash
% brew services list
Name           Status  User  Plist
dbus           stopped       
docker-machine stopped       
emacs          stopped       
postgresql     error   zacky /Users/zacky/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
unbound        stopped       
```

**Comment by zacky1972** [comment]
Thank you for the following reply, @thehaigo 

```
多分 initdbをしていない感じでしょうか？
https://qiita.com/kouki-T/items/d6444b81ce65d6412146
```

I tried it, but I got the same error. Finally, I fixed it, perhaps as follows:

```bash
% brew postinstall postgresql
% rm -rf /usr/local/var/postgres                # Perhaps, it is effective to solve the issue 
% initdb /usr/local/var/postgres -E utf8
% brew services restart postgresql         
```

Then, 
```bash
% brew services list
Name           Status  User  Plist
dbus           stopped       
docker-machine stopped       
emacs          stopped       
postgresql     started zacky /Users/zacky/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
unbound        stopped       
```

I did it!

Then, I tried to execute `psql`:

```bash
% psql
psql: error: FATAL:  database "zacky" does not exist
```

Then,

```bash
 % createdb
% psql
zacky=#
```

I did it!

Then, I create `postgres` user and password:

```bash
% psql postgres
psql (13.3)
Type "help" for help.

postgres=# \password
Enter new password: 
Enter it again: 

postgres=# create role postgres with superuser login password 'postgres';

postgres=# \q
```

Finally, I did `mix ecto.setup`, successfully!

```bash
% mix ecto.setup
The database for LiveCanvas.Repo has been created

17:23:14.564 [info]  Migrations already up
```
